# Performance


- Confusion matrix, 混淆矩阵: in binary clasification: `TP`, `FP`, `TN`, `FN`
```
    P    N  (Real)
P  TP   FN
N  FP   TN
(Test)
```
- Accuracy, 准确度: `sum(TP, TN) / sum(TP, FP, TN, FN)`
- Precision, 精确度: `sum(TP) / sum(TP, FP)`
- Sensitivity, 敏感度/召回率: `sum(TP) / sum(TP, FN)`
- Specifity, 特异度: `sum(TN) / sum(TN, FP)`
- F1 score: `(2 * precision * sensitivity) / (precision + sensitiveity)`

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('IRIS.csv')
df.head(), df.tail(), type(df)

(   sepal_length  sepal_width  petal_length  petal_width      species
 0           5.1          3.5           1.4          0.2  Iris-setosa
 1           4.9          3.0           1.4          0.2  Iris-setosa
 2           4.7          3.2           1.3          0.2  Iris-setosa
 3           4.6          3.1           1.5          0.2  Iris-setosa
 4           5.0          3.6           1.4          0.2  Iris-setosa,
      sepal_length  sepal_width  petal_length  petal_width         species
 145           6.7          3.0           5.2          2.3  Iris-virginica
 146           6.3          2.5           5.0          1.9  Iris-virginica
 147           6.5          3.0           5.2          2.0  Iris-virginica
 148           6.2          3.4           5.4          2.3  Iris-virginica
 149           5.9          3.0           5.1          1.8  Iris-virginica,
 pandas.core.frame.DataFrame)

In [3]:
# 模拟二分类问题，只取最后一百行（涵盖两个品种）
y_org = df.iloc[-100:, 4].values
y_org

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicol

In [4]:
x = df.iloc[-100:, [2,3]].values
x

array([[4.7, 1.4],
       [4.5, 1.5],
       [4.9, 1.5],
       [4. , 1.3],
       [4.6, 1.5],
       [4.5, 1.3],
       [4.7, 1.6],
       [3.3, 1. ],
       [4.6, 1.3],
       [3.9, 1.4],
       [3.5, 1. ],
       [4.2, 1.5],
       [4. , 1. ],
       [4.7, 1.4],
       [3.6, 1.3],
       [4.4, 1.4],
       [4.5, 1.5],
       [4.1, 1. ],
       [4.5, 1.5],
       [3.9, 1.1],
       [4.8, 1.8],
       [4. , 1.3],
       [4.9, 1.5],
       [4.7, 1.2],
       [4.3, 1.3],
       [4.4, 1.4],
       [4.8, 1.4],
       [5. , 1.7],
       [4.5, 1.5],
       [3.5, 1. ],
       [3.8, 1.1],
       [3.7, 1. ],
       [3.9, 1.2],
       [5.1, 1.6],
       [4.5, 1.5],
       [4.5, 1.6],
       [4.7, 1.5],
       [4.4, 1.3],
       [4.1, 1.3],
       [4. , 1.3],
       [4.4, 1.2],
       [4.6, 1.4],
       [4. , 1.2],
       [3.3, 1. ],
       [4.2, 1.3],
       [4.2, 1.2],
       [4.2, 1.3],
       [4.3, 1.3],
       [3. , 1.1],
       [4.1, 1.3],
       [6. , 2.5],
       [5.1, 1.9],
       [5.9,

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(y_org)
le.classes_, le, y_org

(array(['Iris-versicolor', 'Iris-virginica'], dtype=object),
 LabelEncoder(),
 array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iri

In [6]:
y_i = le.transform(y_org)
y_i
# asume that Iris-virginica is positive

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score

In [9]:
print('交叉验证')

y = y_i

# split
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=1).split(x, y)
# print(list(kfold))

scores = []
for k, (train, test) in enumerate(kfold):
    
    # standardization
    sc = StandardScaler()
    sc.fit(x[train])
    x_train_std = sc.transform(x[train])
    x_test_std = sc.transform(x[test])
    
    # fit logistic regression
    lr = LogisticRegression(C=100.0, random_state=k)
    lr.fit(x_train_std, y[train])
    
    # accurate
    score = lr.score(x_test_std, y[test])
    scores.append(score)
    print(f"Fold: {k+1}")
    print(f"Acc: {score: {0}.{3}}")
    
    # predict
    y_pred = lr.predict(x_test_std)
    print("y_true:", y[test])
    print("y_pred:", y_pred)
    
    # confusion_matrix
    conf_mat = confusion_matrix(y_true=y[test], y_pred=y_pred, labels=[1, 0]) # 第一行标签 1， 第二行标签 0
    print(conf_mat)
    
    # precision
    precision = precision_score(y_true=y[test], y_pred=y_pred)
    print("Precision:", precision)
    
    # recall
    recall = recall_score(y_true=y[test], y_pred=y_pred)
    print("Recall:", recall)
    
    # f1 score
    f1 = f1_score(y_true=y[test], y_pred=y_pred)
    print("f1:", f1)
    
    # specifity
    tn = conf_mat[1, 1]
    fp = conf_mat[1, 0]
    specifity = tn / (tn + fp)
    print("specifity:", specifity)
    print()

交叉验证
Fold: 1
Acc:  0.9
y_true: [0 0 0 0 0 1 1 1 1 1]
y_pred: [0 0 0 0 0 0 1 1 1 1]
[[4 1]
 [0 5]]
Precision: 1.0
Recall: 0.8
f1: 0.888888888888889
specifity: 1.0

Fold: 2
Acc:  1.0
y_true: [0 0 0 0 0 1 1 1 1 1]
y_pred: [0 0 0 0 0 1 1 1 1 1]
[[5 0]
 [0 5]]
Precision: 1.0
Recall: 1.0
f1: 1.0
specifity: 1.0

Fold: 3
Acc:  0.9
y_true: [0 0 0 0 0 1 1 1 1 1]
y_pred: [0 1 0 0 0 1 1 1 1 1]
[[5 0]
 [1 4]]
Precision: 0.8333333333333334
Recall: 1.0
f1: 0.9090909090909091
specifity: 0.8

Fold: 4
Acc:  0.9
y_true: [0 0 0 0 0 1 1 1 1 1]
y_pred: [0 0 1 0 0 1 1 1 1 1]
[[5 0]
 [1 4]]
Precision: 0.8333333333333334
Recall: 1.0
f1: 0.9090909090909091
specifity: 0.8

Fold: 5
Acc:  0.9
y_true: [0 0 0 0 0 1 1 1 1 1]
y_pred: [0 0 0 0 0 1 1 0 1 1]
[[4 1]
 [0 5]]
Precision: 1.0
Recall: 0.8
f1: 0.888888888888889
specifity: 1.0

Fold: 6
Acc:  0.9
y_true: [0 0 0 0 0 1 1 1 1 1]
y_pred: [0 0 0 0 0 1 1 0 1 1]
[[4 1]
 [0 5]]
Precision: 1.0
Recall: 0.8
f1: 0.888888888888889
specifity: 1.0

Fold: 7
Acc:  1.0
y_true: [0 